In [1]:
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

In [2]:
training_data = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [3]:
training_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [4]:
Y = training_data.drop(labels=training_data.columns[-1],axis=1)

In [5]:
Y

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

In [6]:
pca = PCA()

In [7]:
projected_X = pca.fit_transform(Y)

In [8]:
projected_X

array([[ 2.54846295e+03, -1.67536843e+03, -1.76694599e+02, ...,
        -3.87855828e+00, -1.17934595e+00,  1.49299273e+00],
       [ 4.48629302e+03, -2.46635269e+03, -3.08054162e+02, ...,
        -3.02456216e+00,  1.69609080e+00,  1.03383083e+00],
       [-2.27125884e+03, -1.55221708e+02,  1.46770304e+01, ...,
        -4.56270822e+00, -2.72238114e+00,  1.76011226e+00],
       ...,
       [-5.74349776e+01, -1.84177704e+02,  3.50888330e+00, ...,
         7.92471923e+00, -3.75001757e-01,  4.81534712e-01],
       [-3.22883092e+01, -1.30812676e+02, -1.61302311e+01, ...,
         7.98808585e+00, -1.26676638e+00,  3.68890616e-01],
       [-1.06113653e+03, -2.13830213e+02,  7.96799915e+01, ...,
         6.42640683e+00, -6.18891334e-01, -5.26953677e-02]])

In [9]:
projected_X = pd.DataFrame(data=projected_X,
                           columns=["Feature_"+str(i) for i in range(1,9)])

In [10]:
projected_X

Feature_1    Feature_2   Feature_3   Feature_4  Feature_5  Feature_6  \
0      2548.462950 -1675.368431 -176.694599  451.797385   1.794425  -3.878558   
1      4486.293020 -2466.352693 -308.054162  839.231263  17.610251  -3.024562   
2     -2271.258841  -155.221708   14.677030   33.190517 -14.830972  -4.562708   
3     -1465.339874  -328.773036  -23.775044   54.142843 -15.831044  -4.701464   
4     -1456.886292  -208.071528  -23.881561   24.562863 -10.580953  -4.731190   
...            ...          ...         ...         ...        ...        ...   
16995  -639.653398  -289.531050   26.383700  -10.491428  22.731611   6.372973   
16996  -366.069656   -78.789431  -58.095235   13.515137   7.018859   6.862207   
16997   -57.434978  -184.177704    3.508883   21.144013 -10.865868   7.924719   
16998   -32.288309  -130.812676  -16.130231   20.183012  -8.996086   7.988086   
16999 -1061.136529  -213.830213   79.679991    4.595604  22.332635   6.426407   

       Feature_7  Feature_8  
0      -1.179346   1.492993  
1       1.696091   1.033831  
2      -2.722381   1.760112  
3      -1.191306   1.843502  
4      -2.508884   1.770503  
...          ...        ...  
16995  -1.339104  -0.009410  
16996  -0.440339  -0.038868  
16997  -0.375002   0.481535  
16998  -1.266766   0.368891  
16999  -0.618891  -0.052695  

[17000 rows x 8 columns]

In [11]:
pca.singular_values_

array([3.21417700e+05, 6.95950997e+04, 2.27142804e+04, 6.67563904e+03,
       1.52267805e+03, 3.70472239e+02, 2.01863382e+02, 6.44590968e+01])

In [12]:
pca.get_covariance()

array([[ 4.02069233e+00, -3.96518544e+00, -2.88355242e+00,
         2.05489998e+02,  6.06853288e+01,  2.34017167e+02,
         4.59746458e+01, -5.92481156e-02],
       [-3.96518544e+00,  4.56822140e+00,  4.42652137e-01,
        -1.80652575e+02, -6.24971957e+01, -2.72963262e+02,
        -6.15585795e+01, -3.27506114e-01],
       [-2.88355242e+00,  4.42652137e-01,  1.58430983e+02,
        -9.90499269e+03, -1.70002683e+03, -4.27500196e+03,
        -1.46531200e+03, -2.78442789e+00],
       [ 2.05489998e+02, -1.80652575e+02, -9.90499269e+03,
         4.75216923e+06,  8.53059831e+05,  2.15236872e+06,
         7.70353377e+05,  8.12729998e+02],
       [ 6.06853288e+01, -6.24971957e+01, -1.70002683e+03,
         8.53059831e+05,  1.77661788e+05,  4.26326445e+05,
         1.58982941e+05, -1.08535966e+01],
       [ 2.34017167e+02, -2.72963262e+02, -4.27500196e+03,
         2.15236872e+06,  4.26326445e+05,  1.31756642e+06,
         4.01317219e+05, -1.39658833e+00],
       [ 4.59746458e+01, -6.155857

In [17]:
Y_zero_mean = Y - Y.mean()

In [18]:
Y_zero_mean = np.array(Y_zero_mean)

In [19]:
sigma_original = (1/Y.shape[0])*np.matmul(Y_zero_mean.T,
                                                   Y_zero_mean)

In [20]:
sigma_original_direct = Y.cov()

In [21]:
sigma_original_direct

longitude    latitude  housing_median_age   total_rooms  \
longitude             4.020692   -3.965185           -2.883552  2.054900e+02   
latitude             -3.965185    4.568221            0.442652 -1.806526e+02   
housing_median_age   -2.883552    0.442652          158.430983 -9.904993e+03   
total_rooms         205.489998 -180.652575        -9904.992690  4.752169e+06   
total_bedrooms       60.685329  -62.497196        -1700.026828  8.530598e+05   
population          234.017167 -272.963262        -4275.001960  2.152369e+06   
households           45.974646  -61.558579        -1465.311997  7.703534e+05   
median_income        -0.059248   -0.327506           -2.784428  8.127300e+02   

                    total_bedrooms    population     households  median_income  
longitude                60.685329  2.340172e+02      45.974646      -0.059248  
latitude                -62.497196 -2.729633e+02     -61.558579      -0.327506  
housing_median_age    -1700.026828 -4.275002e+03   -1465.311997      -2.784428  
total_rooms          853059.831387  2.152369e+06  770353.377150     812.729998  
total_bedrooms       177661.787682  4.263264e+05  158982.941347     -10.853597  
population           426326.444591  1.317566e+06  401317.218749      -1.396588  
households           158982.941347  4.013172e+05  147856.277053       5.608393  
median_income           -10.853597 -1.396588e+00       5.608393       3.641061

In [22]:
sigma_original

array([[ 4.02045581e+00, -3.96495219e+00, -2.88338280e+00,
         2.05477911e+02,  6.06817591e+01,  2.34003402e+02,
         4.59719414e+01, -5.92446305e-02],
       [-3.96495219e+00,  4.56795268e+00,  4.42626098e-01,
        -1.80641948e+02, -6.24935194e+01, -2.72947206e+02,
        -6.15549584e+01, -3.27486849e-01],
       [-2.88338280e+00,  4.42626098e-01,  1.58421663e+02,
        -9.90441004e+03, -1.69992683e+03, -4.27475049e+03,
        -1.46522580e+03, -2.78426410e+00],
       [ 2.05477911e+02, -1.80641948e+02, -9.90441004e+03,
         4.75188969e+06,  8.53009651e+05,  2.15224211e+06,
         7.70308062e+05,  8.12682190e+02],
       [ 6.06817591e+01, -6.24935194e+01, -1.69992683e+03,
         8.53009651e+05,  1.77651337e+05,  4.26301367e+05,
         1.58973589e+05, -1.08529581e+01],
       [ 2.34003402e+02, -2.72947206e+02, -4.27475049e+03,
         2.15224211e+06,  4.26301367e+05,  1.31748891e+06,
         4.01293612e+05, -1.39650618e+00],
       [ 4.59719414e+01, -6.155495

In [23]:
factorized_matrices = np.linalg.svd(sigma_original)

In [24]:
factorized_matrices

(array([[-4.87779818e-05,  4.26597318e-04,  5.96219142e-05,
          4.44385427e-03,  1.75541809e-02,  6.74717920e-01,
          1.55069103e-01,  7.21374533e-01],
        [ 4.83304787e-05, -5.92830386e-04,  1.77408305e-04,
         -1.06187208e-03, -1.74489015e-03, -7.32744210e-01,
          2.49217466e-02,  6.80044316e-01],
        [ 1.81139134e-03,  1.66615756e-03, -3.76947307e-03,
         -1.92770694e-02, -9.99629800e-01,  1.37056902e-02,
         -3.08899604e-03,  1.22883216e-02],
        [-8.78741371e-01, -4.53645869e-01,  1.47944433e-01,
         -1.10543662e-02, -2.69649914e-03,  2.38305870e-04,
          1.38217673e-03, -1.89670088e-04],
        [-1.61685692e-01,  5.45364032e-02, -7.45061966e-01,
          6.44666720e-01, -9.82541906e-03, -1.70970188e-03,
         -8.45312761e-03, -2.97587618e-04],
        [-4.24259252e-01,  8.83742060e-01,  1.93001366e-01,
          4.18662496e-02, -8.38430316e-04, -7.41671896e-04,
         -7.02897990e-04,  4.00401040e-05],
        [-1.4721

In [26]:
projected_X = np.matmul(Y_zero_mean,factorized_matrices[0])

In [27]:
projected_X.shape

(17000, 8)

In [28]:
projected_X = pd.DataFrame(data=projected_X,columns=["Feature_"+str(i) for i in range(1,9)])

In [29]:
projected_X

Feature_1    Feature_2   Feature_3   Feature_4  Feature_5  Feature_6  \
0     -2548.462950 -1675.368431 -176.694599  451.797385  -1.794425   3.878558   
1     -4486.293020 -2466.352693 -308.054162  839.231263 -17.610251   3.024562   
2      2271.258841  -155.221708   14.677030   33.190517  14.830972   4.562708   
3      1465.339874  -328.773036  -23.775044   54.142843  15.831044   4.701464   
4      1456.886292  -208.071528  -23.881561   24.562863  10.580953   4.731190   
...            ...          ...         ...         ...        ...        ...   
16995   639.653398  -289.531050   26.383700  -10.491428 -22.731611  -6.372973   
16996   366.069656   -78.789431  -58.095235   13.515137  -7.018859  -6.862207   
16997    57.434978  -184.177704    3.508883   21.144013  10.865868  -7.924719   
16998    32.288309  -130.812676  -16.130231   20.183012   8.996086  -7.988086   
16999  1061.136529  -213.830213   79.679991    4.595604 -22.332635  -6.426407   

       Feature_7  Feature_8  
0       1.179346   1.492993  
1      -1.696091   1.033831  
2       2.722381   1.760112  
3       1.191306   1.843502  
4       2.508884   1.770503  
...          ...        ...  
16995   1.339104  -0.009410  
16996   0.440339  -0.038868  
16997   0.375002   0.481535  
16998   1.266766   0.368891  
16999   0.618891  -0.052695  

[17000 rows x 8 columns]

In [30]:
projected_X.cov()

Feature_1     Feature_2     Feature_3     Feature_4  \
Feature_1  6.077377e+06  1.915350e-10  9.064493e-11  1.769754e-10   
Feature_2  1.915350e-10  2.849272e+05  2.382614e-10 -1.013695e-10   
Feature_3  9.064493e-11  2.382614e-10  3.035111e+04 -4.416680e-11   
Feature_4  1.769754e-10 -1.013695e-10 -4.416680e-11  2.621575e+03   
Feature_5  3.913155e-11  5.468418e-12 -2.160016e-12 -2.624421e-12   
Feature_6  3.209006e-10  6.487625e-11 -1.647089e-10 -7.449253e-11   
Feature_7  1.290214e-10  9.393814e-12 -3.804980e-11 -1.677843e-11   
Feature_8  9.057268e-11  4.560881e-11 -1.755596e-10 -7.679373e-11   

              Feature_5     Feature_6     Feature_7     Feature_8  
Feature_1  3.913155e-11  3.209006e-10  1.290214e-10  9.057268e-11  
Feature_2  5.468418e-12  6.487625e-11  9.393814e-12  4.560881e-11  
Feature_3 -2.160016e-12 -1.647089e-10 -3.804980e-11 -1.755596e-10  
Feature_4 -2.624421e-12 -7.449253e-11 -1.677843e-11 -7.679373e-11  
Feature_5  1.363932e+02 -2.399575e-12  3.282796e-13  3.396358e-12  
Feature_6 -2.399575e-12  8.073986e+00  9.030182e-12  4.457049e-11  
Feature_7  3.282796e-13  9.030182e-12  2.397131e+00 -2.749485e-12  
Feature_8  3.396358e-12  4.457049e-11 -2.749485e-12  2.444247e-01

In [31]:
n_components = 6

In [32]:
Q = factorized_matrices[0]

In [33]:
Q_tilda = Q[:,0:n_components]

In [34]:
projected_X_dim_reduced = np.matmul(Y_zero_mean,Q_tilda)

In [35]:
projected_X_dim_reduced = pd.DataFrame(data=projected_X_dim_reduced,
                                       columns=["Feature_"+str(i) for i in range(1,7)])

In [36]:
projected_X_dim_reduced

Feature_1    Feature_2   Feature_3   Feature_4  Feature_5  Feature_6
0     -2548.462950 -1675.368431 -176.694599  451.797385  -1.794425   3.878558
1     -4486.293020 -2466.352693 -308.054162  839.231263 -17.610251   3.024562
2      2271.258841  -155.221708   14.677030   33.190517  14.830972   4.562708
3      1465.339874  -328.773036  -23.775044   54.142843  15.831044   4.701464
4      1456.886292  -208.071528  -23.881561   24.562863  10.580953   4.731190
...            ...          ...         ...         ...        ...        ...
16995   639.653398  -289.531050   26.383700  -10.491428 -22.731611  -6.372973
16996   366.069656   -78.789431  -58.095235   13.515137  -7.018859  -6.862207
16997    57.434978  -184.177704    3.508883   21.144013  10.865868  -7.924719
16998    32.288309  -130.812676  -16.130231   20.183012   8.996086  -7.988086
16999  1061.136529  -213.830213   79.679991    4.595604 -22.332635  -6.426407

[17000 rows x 6 columns]

In [37]:
projected_X_dim_reduced.cov()

Feature_1     Feature_2     Feature_3     Feature_4  \
Feature_1  6.077377e+06  1.915350e-10  9.064493e-11  1.769754e-10   
Feature_2  1.915350e-10  2.849272e+05  2.382614e-10 -1.013695e-10   
Feature_3  9.064493e-11  2.382614e-10  3.035111e+04 -4.416680e-11   
Feature_4  1.769754e-10 -1.013695e-10 -4.416680e-11  2.621575e+03   
Feature_5  3.913155e-11  5.468418e-12 -2.160016e-12 -2.624421e-12   
Feature_6  3.209006e-10  6.487625e-11 -1.647089e-10 -7.449253e-11   

              Feature_5     Feature_6  
Feature_1  3.913155e-11  3.209006e-10  
Feature_2  5.468418e-12  6.487625e-11  
Feature_3 -2.160016e-12 -1.647089e-10  
Feature_4 -2.624421e-12 -7.449253e-11  
Feature_5  1.363932e+02 -2.399575e-12  
Feature_6 -2.399575e-12  8.073986e+00